site_name: ProMice
theme:   
  icon:
    admonition:
       note: octicons/tag-16
       abstract: octicons/checklist-16
       info: octicons/info-16
       tip: octicons/squirrel-16
       success: octicons/check-16
       question: octicons/question-16
       warning: octicons/alert-16
       failure: octicons/x-circle-16
       danger: octicons/zap-16
       bug: octicons/bug-16
       example: octicons/beaker-16
       quote: octicons/quote-16
       3D print : material/printer-3d-nozzle
       3D : material/printer-3d
       
  logo: images/Logo_white.png
  name: material
  palette:
    scheme: default
    primary: blue grey
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy
    
nav:
  - Home: index.md
  - System Overview:
    - Structure: architecture.md
    - Mechanical design: mechanical_design.md
    - Sensors: sensors.md
    - Hardware: hardware.md
  - Tutorial: 
    - 3D printing: 3D_printing.md
    - Soldering: soldering.md
    - Assembling & instrumentation : assembling_instrumentation.md
    - Electronics: electronics.md
    - Encoders linearization: encoders_linearization.md
    - Control : control.md
    - Materials: materials.md
    
  
plugins:
  - search
  - table-reader

extra:
  generator: false

markdown_extensions:
  - attr_list
  - pymdownx.blocks.caption
  - pymdownx.betterem
  - tables
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css  
  - https://unpkg.com/katex@0/dist/katex.min.css
